language: elixir

elixir:
  - 1.9.0
  - 1.8.2
  - 1.8.0
  - 1.10.2
otp_release:
  - 21.0
  - 22.0

env:
  global:
    - MIX_ENV=test

cache:
  directories:
    - _build
    - deps

script:
  - mix credo --strict
  - mix test
